baseurl = "https://joe07274.github.io/myblog"
title = "dodo ❤ bobo's blog"
languageCode = "en-us"
disqusShortname = "joe07274"
copyright = "Copyright (c) 2008 - 2019, Steve Francia; all rights reserved."
MetaDataFormat = "toml"
googleAnalytics = "UA-7131036-1"

[author]
    name = "joe07274"

[indexes]
    tag = "tags"
    topic = "topics"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true